## AKS
AKS_GREENFIELD="1"
HAS_2ND_NODEPOOL="1"
AKS_CNI="0"
AKS_KUBENET="1"
PURPOSE="devops"
LOCATION="northeurope"

RG_NAME="rg-aks-"$PURPOSE
CLUSTER_NAME="aks-"$PURPOSE
ACR_NAME="acr"$PURPOSE
#NODE_SIZE="Standard_D4s_v3"
NODE_SIZE="Standard_DS2_v2"
USER_NODE_SIZE="Standard_D4s_v3"
NODE_COUNT="1"
USER_NODE_COUNT="1"
USER_NODE_DISK_SIZE="90"
VMSETTYPE="VirtualMachineScaleSets"
#VMSETTYPE="AvailabilitySet"
VERSION="1.21.2"

# SQL SERVER VARIABLES
SQL_SERVER_USER="sqladmin"
SQL_SERVER_PASSWORD="P2ssw0rd1234"
SQL_SERVER_NAME="sql-tmcmm"
SQL_DATABASE_NAME="sql-database"
FIREWALL_RULE_NAME="sql-fw-rule"

## Networking
VNET_RG=$RG_NAME
GENERIC_ADMIN_USERNAME="azureuser"
CNI_PLUGIN="cni"
AKS_VNET="vnet-"$CLUSTER_NAME
AKS_VNET_RG="rg-vnet-"$CLUSTER_NAME
AKS_SNET="snet-"$PURPOSE
############################
AKS_VNET_CIDR="10.0.0.0/16"
AKS_SNET="snet-"$PURPOSE
AKS_SNET_CIDR="10.0.0.0/22"
AKS_CLUSTER_SRV_CIDR="10.0.4.0/23"
AKS_CLUSTER_DNS="10.0.4.10"
AKS_POD_CIDR="10.244.0.0/16"
AKS_CLUSTER_DOCKER_BRIDGE="172.17.0.1/16"
MY_HOME_PUBLIC_IP=$(curl ifconfig.io)
## IDENTITY
RG_IDENTITY_LOCATION=$LOCATION
RG_IDENTITY_NAME=$RG_NAME
IDENTITY_NAME="aplication-identity"
POD_IDENTITY_NAME="pod-identity"
POD_IDENTITY_NAMESPACE="my-app"

#AKS_VNET_CIDR="10.150.0.0/17"
#AKS_SNET_CIDR="10.150.110.0/24"
#AKS_CLUSTER_SRV_CIDR="10.0.0.0/16"
#AKS_CLUSTER_DNS="10.0.0.10"
#AKS_POD_CIDR="10.244.0.0/16"
#AKS_CLUSTER_DOCKER_BRIDGE="172.17.0.1/16"
#MY_HOME_PUBLIC_IP=$(curl ifconfig.io)
#########################################
